org: jgeorge97
console: true
service: ecommerce-api-serverless #Name of your App

provider:
  name: aws
  runtime: nodejs14.x # Node JS version
  memorySize: 512
  timeout: 10
  stage: production
  region: ap-south-1 # AWS region

functions:
  api:
    handler: lambda.universal
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
